devicetype = {0: "WHO",
              1: "CAMERA",
              2: "APP",
              3: "FLYC",
              4: "GIMBAL",
              5: "CENTER",
              6: "RC",
              7: "WIFI",
              8: "DM368",
              9: "OFDM - OSD",
              10: "PC",
              11: "BATTERY",
              12: "DIGITAL",
              13: "DM368_G",
              14: "OSD",
              15: "TRANSFORM",
              16: "TRANSFORM_G",
              17: "SINGLE",
              18: "DOUBLE",
              19: "FPGA",
              20: "FPGA_G",
              26: "GPS",
              27: "WIFI_G",
              28: "GLASS",
              0x1f: "BROADCAST",
              100: "OTHER", }
