devicetype = {0: "WHO",
              1: "CAMERA",
              2: "APP",
              3: "FLYC",
              4: "GIMBAL",
              5: "CENTER",
              6: "RC",
              7: "WIFI",
              8: "DM368",
              9: "OFDM - OSD",
              10: "PC",
              11: "BATTERY",
              12: "DIGITAL",
              13: "DM368_G",
              14: "OSD",
              15: "TRANSFORM",
              16: "TRANSFORM_G",
              17: "SINGLE",
              18: "DOUBLE",
              19: "FPGA",
              20: "FPGA_G",
              26: "GPS",
              27: "WIFI_G",
              28: "GLASS",
              0x1f: "BROADCAST",
              100: "OTHER", }

commandsets = {0: "COMMON",
               1: "SPECIAL",
               2: "CAMERA",
               3: "FLYC",
               4: "GIMBAL",
               5: "CENTER",
               6: "RC",
               7: "WIFI",
               8: "DM368",
               9: "OSD",
               10: "EYE",
               11: "SIMULATOR",
               12: "BATTERY",
               13: "SMARTBATTERY",
               15: "RTK",
               17: "ADS_B",
               21: "GLASS",
               24: "MODULE4G",
               25: "ONBOARDSDK",
               34: "FLYC2",
               60: "PAYLOADSDK",
               73: "SDKAGENT",
               0x1F: "FLIGHT",
               0x20: "NARROWBAND",
               0xEE: "RECOGNIZE",
               100: "OTHER", }

commandtypes = {0: "REQUEST",
                1: "ACK", }

encryptiontypes = {0: "NO",
                   1: "DIC",
                   2: "OTHER",
                   3: "SIMPLE", }

ackTypes = {0: "NO",
       1: "YES_BY_PUSH",
       2: "YES", }
